# Generated by Django 3.2.24 on 2024-02-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accepted'), ('reject', 'Rejected')], default='pending', max_length=10),
        ),
    ]
